# Generated by Django 5.1 on 2024-08-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название действия')),
                ('description', models.TextField(verbose_name='Описание действия')),
                ('image', models.ImageField(upload_to='action_image', verbose_name='фото')),
                ('desc_image', models.CharField(max_length=255, verbose_name='Описание фото')),
            ],
            options={
                'verbose_name': 'действие',
                'verbose_name_plural': 'действии',
            },
        ),
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'О нас', 'verbose_name_plural': 'О нас'},
        ),
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.TextField(verbose_name='Описание информации'),
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название информации'),
        ),
    ]
