# Generated by Django 5.1 on 2024-08-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='photo2',
            field=models.ImageField(default=1, upload_to='actional_image', verbose_name='фотки'),
            preserve_default=False,
        ),
    ]
