# Generated by Django 5.1 on 2024-08-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Фио')),
                ('description', models.TextField(verbose_name='Деятельность')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'неймес',
            },
        ),
    ]
