# Generated by Django 5.1 on 2024-08-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='image',
            field=models.ImageField(default=1, upload_to='jobs', verbose_name='Фото'),
            preserve_default=False,
        ),
    ]
