# Generated by Django 5.1 on 2024-08-16 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_jobs_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Create',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='опять название')),
                ('description', models.TextField(verbose_name='опять описание')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'криэйшны ',
            },
        ),
    ]
