# Generated by Django 5.1 on 2024-08-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_create_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='название анимации')),
                ('description', models.TextField(verbose_name='описание анимации')),
                ('image', models.ImageField(upload_to='jobs', verbose_name='Фото')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'анимация',
            },
        ),
    ]
