# Generated by Django 5.1 on 2024-08-16 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_animation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animation',
            options={'verbose_name': '', 'verbose_name_plural': 'анимации'},
        ),
    ]
