# Generated by Django 5.1 on 2024-08-16 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_animation_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Animation',
        ),
    ]
