# Generated by Django 5.1 on 2024-08-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='название общении')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'общении',
            },
        ),
    ]
