# Generated by Django 5.1 on 2024-08-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_conversation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='кол во клиентов')),
                ('description', models.TextField(verbose_name='описание клиента')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'клиенты',
            },
        ),
    ]
