# Generated by Django 5.1 on 2024-08-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_clients'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='тайтл')),
                ('description', models.TextField(verbose_name='описание тайтла')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'сервисы',
            },
        ),
    ]
