# Generated by Django 5.1 on 2024-08-16 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='название дизайна')),
                ('description', models.TextField(verbose_name='описание дизайна')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'дизайны',
            },
        ),
    ]
