# Generated by Django 5.1 on 2024-08-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_plans'),
    ]

    operations = [
        migrations.CreateModel(
            name='Standart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='вид')),
                ('description', models.TextField(verbose_name='описание ')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'стандарты',
            },
        ),
    ]
